[[constraint]]
  name = "github.com/joho/godotenv"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/knq/jwt"

[[constraint]]
  branch = "master"
  name = "github.com/lib/pq"

[[constraint]]
  branch = "master"
  name = "github.com/matryer/way"

[prune]
  go-tests = true
  unused-packages = true

[metadata.heroku]
  root-package = "github.com/nicolasparada/go-passwordless-demo"
  go-version = "go1.10.3"
